bot:
  token : YOUR_BOT_TOKEN
  prefix: "!a"
  server_id: THE_SERVER_ID
  log_channel_id: THE_LOG_CHANNEL_ID
  general_channel: THE_GENERAL_CHANNEL_ID
  Online_Status: True
  Online_channel_id: THE_ONLINE_CHANNEL_ID
  Player_in_voice : True
  Player_in_voice_channel_id: THE_VOICE_CHANNEL_ID

openai:
  api_key: YOUR_API_KEY


